plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.seleniumhq.selenium:selenium-java:4.40.0")
    testImplementation("org.testng:testng:7.11.0")

    implementation("io.github.bonigarcia:webdrivermanager:6.3.4")

}

test {
    useTestNG() {
        suites "src/test/resources/testng.xml"
    }

}
